language: cpp

compiler:
  - gcc

# by default Ubuntu Precise is included
# this results on 3 build configurations:
# Ubuntu Precise and Trusty + Latest OSX image
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8

addons:
  apt:
    packages:
      - cmake
      - libqt4-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libprotobuf-dev 
      - protobuf-compiler 
      - libode-dev
      - libboost-dev

before_cache:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cleanup ; fi

cache:
  directories:
    - /usr/local/Cellar/openssl
    - /usr/local/opt/openssl
    - /usr/local/Cellar/libevent
    - /usr/local/opt/libevent
    - /usr/local/Cellar/check
    - /usr/local/opt/check
before_install:
  - test -d /usr/local/opt/openssl/lib  || { rmdir /usr/local/opt/openssl; brew install openssl; }
  - test -d /usr/local/opt/libevent/lib || { rmdir /usr/local/opt/libevent; brew install libevent; }
  - test -d /usr/local/opt/check/lib    || { rmdir /usr/local/opt/check; brew install check; }

cache:
  directories:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then $HOME/Library/Caches/Homebrew ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/Cellar/openssl      ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/opt/openssl         ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/Cellar/qt@4         ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/opt/qt@4            ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/Cellar/sqlite       ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/opt/sqlite          ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/Cellar/python/3.7.2       ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/opt/python/3.7.2          ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/Cellar/sphinx-doc       ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/opt/sphinx-doc          ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/Cellar/python@2/2.7.15_1       ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/opt/python@2/2.7.15_1          ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/Cellar/ode/0.15.2_2       ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/opt/ode/0.15.2_2          ; fi
before_install:
  - test -d /usr/local/opt/openssl/lib             || { rm -rf /usr/local/opt/openssl; }
  - test -d /usr/local/opt/qt@4/lib                || { rm -rf /usr/local/opt/qt@4;    }
  - test -d /usr/local/opt/sqlite/lib              || { rm -rf /usr/local/opt/check; }
  - test -d /usr/local/opt/python/3.7.2/lib        || { rm -rf /usr/local/opt/python/3.7.2; }
  - test -d /usr/local/opt/sphinx-doc/lib          || { rm -rf /usr/local/opt/sphinx-doc; }
  - test -d /usr/local/opt/python@2/2.7.15_1/lib   || { rm -rf /usr/local/opt/python@2/2.7.15_1; }
  - test -d /usr/local/opt/protobuf/3.6.1.3_1/lib  || { rm -rf /usr/local/opt/protobuf/3.6.1.3_1; }
  - test -d /usr/local/opt/ode/0.15.2_2/lib        || { rm -rf /usr/local/opt/ode/0.15.2_2; }
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update > /dev/null                   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap cartr/qt4                        ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap-pin cartr/qt4                    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt@4                         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew uninstall --ignore-dependencies python ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install protobuf                     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap robotology/formulae              ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install robotology/formulae/ode      ; fi

install:
  # vartypes
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git clone https://github.com/szi/vartypes.git ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then git clone https://github.com/lordhippo/vartypes.git -b osx-fix; fi
  - cd vartypes
  - mkdir build && cd build
  - cmake ..
  - make
  - sudo make install

script:
  # grsim
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build
  - cmake ..
  - make
  - sudo make install
